spring:
  data:
    mongodb:
      database: library
      host: localhost
      port: 27017
  main:
    allow-circular-references: true
input:
  retriesThreshold: 3
logging:
  level:
    root: info
mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  migration-scan-package:
    - com.study.spring.library.changelog