spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/libraryDB
    username: dbuser
    password: userPASS
    driver-class-name: "org.postgresql.Driver"
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/db.changelog-master.yml"
  main:
    allow-circular-references: true
input:
  retriesThreshold: 3