version: '3.1'

services:
  db:
    image: mongo
    restart: always
    networks:
      - net
    ports:
      - "27017:27017"
  app:
    image: library:1.0
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - net
networks:
  net: {}