server:
  port: 8001

## Standalone Eureka settings
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: 'http://localhost:8001/eureka'
  server:
    wait-time-in-ms-when-sync-empty: 5
    registry-sync-retries: 3
    max-threads-for-peer-replication: 0